### PR TITLE
Fixes ignoring scope on refresh token call

### LINKED ISSUE #104: Scope in refresh_token grant type is ignored.
While checking the compliance of the `refresh_token` grant. I discovered that the optional scope parameter in the body is ignored.

https://github.com/node-oauth/node-oauth2-server/blob/1b91ddc5ddc4bf75a6b6d8548b27591b9750e338/lib/grant-types/refresh-token-grant-type.js#L64-L73

https://datatracker.ietf.org/doc/html/rfc6749#section-6

### PR DESCRIPTION
**Pull request by jorenvandeweyer**
## Summary

- Fixes #104 
- Rewrote scopes to only allow an array of strings instead of where before both a string and an array of strings were allowed.
- Validate scopes safely
*BREAKING: `validateScope` must now only return an array of strings or a falsy value.*
- Updated docs (also removed places still mentioning callbacks)

## Linked issue(s)

#104 #194

## Involved parts of the project

Scopes

## Added tests?

Yes & updated existing tests

## OAuth2 standard

See #104

### CODE REVIEW

File: lib/server.js [hunk 1]
```diff
@@ -26,14 +26,9 @@ class OAuth2Server {
 
   /**
  * Authenticate a token.
- * Note, that callback will soon be deprecated!
  */
 
   authenticate (request, response, options) {
-    if (typeof options === 'string') {
```
Comment (jorenvandeweyer) [inline lib/server.js:33]: I removed this completely since it was not supporting al allowed scope input values. This was also not clearly documented.

File: lib/server.js [hunk 2]
```diff
@@ -26,14 +26,9 @@ class OAuth2Server {
...
-      options = {scope: options};
-    }
-
```
Comment (jorenvandeweyer) [inline lib/server.js:36]: I removed this completely since it was not supporting al allowed scope input values. This was also not clearly documented

**Comment by jorenvandeweyer** [comment]
@jankapunkt I targeted the PR to the `release-5.0.0` branch to avoid merge conflicts since this branch is ahead of `development`

I think we should asap merge `release-5.0.0` into `development`. We can do this before or after merging this PR.

**Comment by shrihari-prakash** [comment]
@jankapunkt , @jorenvandeweyer , will there be one more RC to test this change? I think this is already breaking with my project and maybe I can do a code change and test this to see if things are smooth before 5.0.0?

**Comment by jorenvandeweyer** [comment]
@jankapunkt can there be a RC of this PR?

**Comment by jankapunkt** [comment]
Hi @jorenvandeweyer @shrihari-prakash I was sick the last days jost got back today :dizzy: I will merge later today and create an rc

File: lib/utils/scope-util.js [hunk 3]
```diff
@@ -0,0 +1,16 @@
+const isFormat = require('@node-oauth/formats');
+const InvalidScopeError = require('../errors/invalid-scope-error');
+
+module.exports = {
+  parseScope: function (requestedScope) {
```
Comment (jankapunkt) [inline lib/utils/scope-util.js:5]: Please run the tests with code coverage and if there is missing coverage then please add a unit-test file for this module, testing the parseScope standalone against the cases:

- valid format
  - single word
  - multiple words
  - null
- invalid format
  - single word
  - multiple words

if the other tests already cover this method entirely, please ignore

File: lib/utils/scope-util.js [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+    if (!isFormat.nqschar(requestedScope)) {
+      throw new InvalidScopeError('Invalid parameter: `scope`');
+    }
+
+    if (requestedScope == null) {
```
Comment (jankapunkt) [inline lib/utils/scope-util.js:10]: is this block ever reachable? I think `null` would fail the above test `isFormat.nqschar`, right?

File: lib/grant-types/refresh-token-grant-type.js [hunk 5]
```diff
@@ -142,6 +145,33 @@ class RefreshTokenGrantType extends AbstractGrantType {
 
     return this.model.saveToken(token, client, user);
   }
+
+  getScope (request, token) {
```
Comment (jankapunkt) [inline lib/grant-types/refresh-token-grant-type.js:149]: can you shortly elaborate on this, why it replaced the former behaviour?

**Review by jankapunkt — COMMENTED** [review]
@jorenvandeweyer I added some comments, can we shortly discuss before merging?

**Comment by jankapunkt** [comment]
@jorenvandeweyer would you mind shortly reviewing my comments? I think it's ready to merge I just want to make sure there is nothing missing etc. I can create a new release ASAP once it's merged

File: lib/utils/scope-util.js (hunk 4 above)
Comment (jorenvandeweyer) [reply lib/utils/scope-util.js:10]: `null` is allowed in the above check

File: lib/grant-types/refresh-token-grant-type.js (hunk 5 above)
Comment (jorenvandeweyer) [reply lib/grant-types/refresh-token-grant-type.js:149]: The former behaviour ignored the `scope` parameter passed with the data of the `refresh_token` grant type 

The scope was directly reused from the refresh token

`return this.saveToken(token.user, client, token.scope);`

now we use the scope which is parsed and validated from this function

```
const scope = this.getScope(request, token);
return this.saveToken(token.user, client, scope);
```

This function 
- takes the requested scope and the original scope
- parses them as described in the spec
- checks if there are no extra scopes passed which were not included in the previous token

File: lib/utils/scope-util.js (hunk 3 above)
Comment (jorenvandeweyer) [reply lib/utils/scope-util.js:5]: All those cases were previously already covered.

I forgot a single line to cover, so I fixed this by adding one more test!

**Comment by jorenvandeweyer** [comment]
@jankapunkt sorry for the delay, I updated the PR.

It should be ready to be merged now!

**Review by jankapunkt — APPROVED** [review]
