### PR TITLE
tests: add deep integration tests

### LINKED ISSUE #219: Insufficient integration tests
**Specify your setup**

- version of @node-oauth/oauth2-server: 5.0.0-rc.1

**Describe the bug**

The integration tests do not properly cover the regressions, introduced by the switch to native async/await. This is due to the original integration tests do not really test, whether the correct values are passed to the model as most model functions are not covering parameters or return nearly nothing.

This already resulted in:

- https://github.com/node-oauth/node-oauth2-server/issues/217
- https://github.com/node-oauth/node-oauth2-server/issues/204

Proposal:

All integration tests should also cover proper model testing.

We should target this for 5.0.0, because there may be more parts affected as may have been revealed yet.

### PR DESCRIPTION
**Pull request by jankapunkt**
## Summary

This PR improves the integration tests to cover integrity of the model parameters.

Furthermore, compliance tests are added, where possible.

Finally, coverage is improved, if possible.

## Linked issue(s)

#219 

## Involved parts of the project

Tests, grant types, handlers

## OAuth2 standard

Compliance tests to deeply conform RFC 6749

## Reproduction

checkout branch, run `npm run test` or `npm run test:coverage`

### CODE REVIEW

File: test/compliance/client-credential-workflow_test.js [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+      ('refresh_token' in response.body).should.equal(false);
+
+      token.accessToken.should.be.a('string');
+      token.accessTokenExpiresAt.should.be.a('date');
+      ('refreshToken' in token).should.equal(false);
+      ('refreshTokenExpiresAt' in token).should.equal(false);
+      token.scope.should.equal(enabledScope);
+
+      db.accessTokens.has(token.accessToken).should.equal(true);
+      db.refreshTokens.has(token.refreshToken).should.equal(false);
```
Comment (jorenvandeweyer) [inline test/compliance/client-credential-workflow_test.js:103]: why should there be no refresh token?

**Review by jorenvandeweyer — APPROVED** [review]
I already did a review. These tests are getting some meaning now!

Since it are mostly tests, I think you should already merge it. 
_(It takes a lot of time to review a PR as large as this one. Personally I prefer a lot of small PR's instead of 1 big PR 😅 )_

File: test/integration/handlers/authorize-handler_test.js [hunk 2]
```diff
@@ -543,32 +619,119 @@
...
+      const state = 'fooobarstatebaz';
+      const scope = 'read';
+      const client = {
+        id: 'client-1322132131',
+        grants: ['authorization_code'],
+        redirectUris: ['http://example.com/cb']
+      };
+      const authorizationCode = 'long-authz-code-?';
+      const accessTokenDoc = {
+        accessToken: 'some-access-token-code-?',
```
[the remark this answers is not in the document]
Comment (jankapunkt) [reply test/integration/handlers/authorize-handler_test.js:640]: This is just tests, can be ignored

File: test/compliance/client-credential-workflow_test.js (hunk 1 above)
Comment (jankapunkt) [reply test/compliance/client-credential-workflow_test.js:103]: The tests only cover [client credential grant (section 4.4)](https://datatracker.ietf.org/doc/html/rfc6749.html#section-4.4) and there is explicitly stated:

```
[4.4.3](https://datatracker.ietf.org/doc/html/rfc6749.html#section-4.4.3).  Access Token Response

   If the access token request is valid and authorized, the
   authorization server issues an access token as described in
   [Section 5.1](https://datatracker.ietf.org/doc/html/rfc6749.html#section-5.1).  A refresh token SHOULD NOT be included.  If the request
   failed client authentication or is invalid, the authorization server
   returns an error response as described in [Section 5.2](https://datatracker.ietf.org/doc/html/rfc6749.html#section-5.2).

   An example successful response:

     HTTP/1.1 200 OK
     Content-Type: application/json;charset=UTF-8
     Cache-Control: no-store
     Pragma: no-cache

     {
       "access_token":"2YotnFZFEjr1zCsicMWpAA",
       "token_type":"example",
       "expires_in":3600,
       "example_parameter":"example_value"
     }
```

**Comment by jankapunkt** [comment]
@jorenvandeweyer you are right, let's merge and open a "Part II" PR for this

File: test/compliance/client-credential-workflow_test.js (hunk 1 above)
Comment (jankapunkt) [reply test/compliance/client-credential-workflow_test.js:103]: I think this is, because in CCG there is usually no human involved and the server already stores the secret, ready to be accessed for getting a new access token and the server can also check the expiration before making a call so one could say this is up to your implementation to obtain a new access token before expiration
